window.companyInfo = [
    {"company": "GE", "link":"https://www.ge.com", "img":"generalelectric.png"},
    {"company": "TOYOTA", "link":"https://www.toyota.com", "img":"toyota.png"},
    {"company": "Brown Brothers Harriman", "link":"https://www.bbh.com/en-us", "img":"brownbrothersharriman.png"},
    {"company": "Zebra Technologies", "link":"https://www.zebra.com/us/en.html", "img":"zebratechnologies.png"},
    {"company": "MTA", "link":"http://www.mta.info", "img":"mta.png"},
    {"company": "Citi Bank", "link":"https://online.citi.com/US/login.do", "img":"citi.png"},
    {"company": "Hexcel", "link":"http://www.hexcel.com", "img":"hexcel.png"},
    {"company": "Google", "link":"http://www.google.com", "img":"google.png"},
    {"company": "Coco Cola", "link":"http://www.coca-cola.com/global/", "img":"cococola.png"},
    {"company": "Daikin", "link":"http://www.northamerica-daikin.com", "img":"daikin.png"},
    {"company": "Alcoa", "link":"https://www.alcoa.com/global/en/home.asp", "img":"alcoa.png"},
    {"company": "Amazon", "link":"https://www.amazon.com/", "img":"amazon.png"},
    {"company": "UTC Aerospace Systems", "link":"https://www.utcaerospacesystems.com/", "img":"utcaerospacesystems.png"},
    {"company": "American Water", "link":"https://amwater.com", "img":"americanwater.png"},
    {"company": "IBM", "link":"http://www.ibm.com", "img":"ibm.png"},
    {"company": "Northtop Grumman", "link":"http://www.northtopgrumman.com", "img":"northtopgrumman.png"},
    {"company": "Tata", "link":"www.tata.com", "img":"tata.png"},
    {"company": "Dassault Systems", "link":"https://www.3ds.com", "img":"dassaultsystemes.png"},
    {"company": "Jasmine Universe", "link":"https://www.jasmineuniverse.com", "img":"jasmine.jpg"},
    {"company": "Space X", "link":"http://www.spacex.com", "img":"spacex.png"},
    {"company": "General Dynamics", "link":"http://www.gd.com", "img":"generaldynamics.png"},
    {"company": "Harris", "link":"http://www.harris.com", "img":"harris.jpg"},
    {"company": "HBO", "link":"https://www.hbo.com", "img":"hbo.png"},
    {"company": "John Deere", "link":"https://www.deere.com/en/index.html", "img":"johndeere.png"},
    {"company": "Leviton", "link":"https://www.leviton.com", "img":"leviton.png"},
    {"company": "LiRo Group", "link":"https://www.liro.com", "img":"lirogroup.png"},
    {"company": "Nature's Bounty", "link":"https://www.naturesbountyco.com/", "img":"nbty.png"},
    {"company": "Parsons Brinckerhoff", "link":"https://www.wsp.com/en-US", "img":"parsonsbrickernoff.png"},
    {"company": "Raytheon", "link":"/media/home/portfolio/employers/raytheon.png", "img":"raytheon.png"},
    {"company": "Eaton", "link":"https://www.eaton.com/us/en-us.html", "img":"eaton.png"},
    {"company": "Cognizant", "link":"https://www.cognizant.com", "img":"cognizant.png"},
    {"company": "Fluor", "link":"https://www.fluor.com", "img":"fluor.png"},
];
