window.oncampusInfo = [
    {"company": "AICHE", "link":"https://www.aiche.org", "img":"aiche.png"},
    {"company": "Motor Sports", "link":"http://me.eng.sunysb.edu/~motorsports/", "img":"motorsportslogo.jpg"},
    {"company": "Solar Racing", "link":"https://sbusolarracing.weebly.com", "img":"solar.png"},
    {"company": "Stony Brook Computing Society", "link":"https://www.sbcs.io", "img":"sbcs.png"},
    {"company": "MTA", "link":"http://www.mta.info", "img":"mta.png"},
    {"company": "BMES", "link":"https://www.bme.sunysb.edu/BMES/", "img":"bmes.png"},
    {"company": "CASB", "link":"", "img":"casb.jpg"},
    {"company": "IEEE", "link":"http://www.ieee.org", "img":"ieee.gif"},
    {"company": "SB Robotics", "link":"https://stonybrook.campuslabs.com/engage/organization/Robotics", "img":"sbrt.png"},
    {"company": "iCreate", "link":"https://www.stonybrook.edu/icreate", "img":"innovation.png"},
    {"company": "SASE", "link":"https://saseconnect.org/", "img":"sase.png"},
    {"company": "PUSO-Modern", "link":"https://sites.google.com/site/sbupusosdance/puso-modern", "img":"puso.jpg"},
    {"company": "VSA", "link":"https://www.facebook.com/sbuvsa/", "img":"vsa.jpg"},
    {"company": "NSPE", "link":"https://www.nspe.org/", "img":"nspe.jpg"},
    {"company": "Soceity Of Women Engineers", "link":"http://societyofwomenengineers.swe.org", "img":"swe_logo.png"},
    {"company": "Society of Hispanic Profeesional Engineers", "link":"http://www.shpe.org", "img":"shpe.jpg"},
    {"company": "ASCE", "link":"http://www.asce.org", "img":"asce.png"},
    {"company": "FSA", "link":"https://www.stonybrook.edu/commcms/fsa/", "img":"fsa.png"},
    {"company": "TLT", "link":"https://apps.tlt.stonybrook.edu", "img":"tlt.gif"},
];
